### ISSUE TITLE
Maddy seems to retry after permanent failures

### ISSUE THREAD

**Issue by reivilibre** [foxcpp/maddy#328] opened 2021-01-14 20:13 UTC
# Describe the bug

Perhaps this is because Maddy is not managing to generate a DSN for some reason (#327), but it looks like Maddy is retrying delivery of e-mails, even after they have had a permanent error.

# Steps to reproduce

# Log files

```
submission: incoming message        {"msg_id":"2f6f32e9","sender":"me@home.net","src_host":"[192.168.1.20]","src_ip":"x:47740","username":"me@home.net"}
submission: RCPT ok        {"msg_id":"2f6f32e9","rcpt":"nobody@example.com"}
submission: accepted        {"msg_id":"2f6f32e9"}
queue: delivery attempt failed        {"msg_id":"2f6f32e9","rcpt":"nobody@example.com","reason":"Domain does not accept email (null MX)","smtp_code":556,"smtp_enchcode":"5.1.10","smtp_msg":"Domain does not accept email (null MX)"}
queue: not delivered, permanent error        {"msg_id":"2f6f32e9","rcpt":"nobody@example.com"}
queue: generated failed DSN        {"dsn_id":"b77c542c","msg_id":"2f6f32e9"}
msgpipeline: no check action        {"check":"verify_dkim",m"hasg_id":"b77c542c","reason":"No DKIM signatures","smtp_code":550,"smtp_enchcode":"5.7.20","smtp_msg":"No DKIM signatures"}

---- restart here ----

queue: delivery attempt failed        {"msg_id":"2f6f32e9","rcpt":"nobody@example.com","reason":"Domain does not accept email (null MX)","smtp_code":556,"smtp_enchcode":"5.1.10","smtp_msg":"Domain does not accept email (null MX)"}
queue: not delivered, permanent error        {"msg_id":"2f6f32e9","rcpt":"nobody@example.com"}
queue: generated failed DSN        {"dsn_id":"bde6fe5f","msg_id":"2f6f32e9"}
msgpipeline: no check action        {"check":"verify_dkim","msg_id":"bde6fe5f","reason":"No DKIM signatures","smtp_code":550,"smtp_enchcode":"5.7.20","smtp_msg":"No DKIM signatures"}
```

# Configuration file

https://hastebin.com/raw/leriyabube

# Environment information

* maddy version: Maddy says `maddy 0.5.0-dev15+ge4ad3bd linux/amd64 go1.14.7` but I actually built it from source from the v0.4.3 release cd1d52764ca8e39233e8a53a831f9066d997b763.

Notable config changes: I use Dovecot for mailbox handling.

**I've had to clear out the remote_queue (`rm -r remote_queue` and then restart) because I was worried about the... reputation impact... of keeping retrying all the e-mails I've tried to send over the last month that have been eaten and even permanently rejected.**

**Comment by reivilibre** [comment] 2021-01-16 17:27
This has stopped happening since #327 was fixed. I'm not sure if it's worth fixing — should failure to generate a DSN lead to the e-mail being retried later on?

I will leave this open but if it's not worth worrying about, I have nothing against you closing it. Thanks for your help :).

**Comment by foxcpp** [comment] 2021-01-16 17:34
>should failure to generate a DSN lead to the e-mail being retried later on?

No, it should not - there is a mild chance for abuse. What is happening is not the intended behavior.

**Comment by foxcpp** [comment] 2021-01-16 18:27
The cause for this one problem is rather simple - if emitDSN hangs (e.g. #327) then removeFromDisk never gets called and delivery is reattempted after server restarts since disk metadata for queue entry is still there.
```go
// Generate DSN for recipients that failed permanently this time.
if len(failedRcpts) != 0 {
        q.emitDSN(meta, header, failedRcpts)
}
// No recipients to try, either all failed or all succeeded.
if len(newRcpts) == 0 {
        q.removeFromDisk(meta.MsgMeta)
        return
}
```

**Comment by foxcpp** [comment] 2021-01-16 18:44
I guess this should be closed. Everything done from emitDSN should have reasonable timeouts and deadlocks should be fixed.

**Closed as completed by foxcpp** 2021-01-16 18:44 UTC
Labels: bug, mta-out
