### ISSUE TITLE
maddy fails to build on macOS Catalina

### ISSUE THREAD

**Issue by herbygillot** [foxcpp/maddy#318] opened 2020-12-06 02:01 UTC
# Describe the bug

`build.sh` fails to build on macOS 10.15.7 with the following error:

```
--- Building main executable...
# runtime/cgo
ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

So `build.sh` is hard-coding certain `LDFLAGS` that are not compatible with macOS' `ld`.

# Steps to reproduce

Checkout and attempt to build `maddy` on macOS Catalina.

# Environment information

* maddy version: (master), commit `1bfaa3995b7a2f23b22b4e2af21c4460852451e1`
* macOS 10.15.7 19H15
* Xcode 12.2 12B45b
* /usr/bin/clang:
```
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by hugmouse** [comment] 2020-12-06 02:11
Couldn't reproduce your bug, but found a different one. 

Also there is some updates, latest commit is `27ec4fa57da9830824a04d839efa43e8d97b97ce` -- you can try newer `build.sh`.

Tested MacOS 11.0.1: 

**Log**

```
mysh@myshs-MacBook-Pro maddy % ./build.sh
-- Version: 0.4.3-dev+27ec4fa
-- Building maddy
go: downloading github.com/emersion/go-smtp v0.13.1-0.20200724113925-09421d11e5b0
go: downloading github.com/emersion/go-imap-unselect v0.0.0-20171113212723-b985794e5f26
go: downloading github.com/emersion/go-msgauth v0.6.3-0.20201124115313-816fefe10e5d
go: downloading github.com/emersion/go-imap-idle v0.0.0-20200601154248-f05f54664cc4
go: downloading github.com/foxcpp/go-imap-sql v0.4.1-0.20200823124337-2f57903a7ed0
go: downloading github.com/emersion/go-message v0.13.0
go: downloading github.com/emersion/go-imap v1.0.6-0.20201022142522-f9d60f89af32
go: downloading github.com/emersion/go-imap-appendlimit v0.0.0-20190308131241-25671c986a6a
go: downloading github.com/emersion/go-milter v0.3.0
go: downloading github.com/prometheus/client_golang v1.7.1
go: downloading golang.org/x/net v0.0.0-20200822124328-c89045814202
go: downloading github.com/foxcpp/go-dovecot-sasl v0.0.0-20200522223722-c4699d7a24bf
go: downloading blitiri.com.ar/go/spf v1.1.1
go: downloading github.com/foxcpp/go-imap-i18nlevel v0.0.0-20200208001533-d6ec88553005
go: downloading golang.org/x/text v0.3.5-0.20201125200606-c27b9fd57aec
go: downloading github.com/GehirnInc/crypt v0.0.0-20200316065508-bb7000b8a962
go: downloading github.com/mattn/go-sqlite3 v2.0.3+incompatible
go: downloading github.com/emersion/go-imap-specialuse v0.0.0-20200722111535-598ff00e4075
go: downloading github.com/emersion/go-imap-compress v0.0.0-20170105185004-f036eda44681
go: downloading github.com/miekg/dns v1.1.31
go: downloading github.com/emersion/go-textwrapper v0.0.0-20160606182133-d0e65e56babe
go: downloading github.com/emersion/go-sasl v0.0.0-20200509203442-7bfe0ed36a21
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/emersion/go-imap-sortthread v1.1.1-0.20200727121200-18e5fb409fed
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/emersion/go-imap-move v0.0.0-20190710073258-6e5a51a5b342
go: downloading golang.org/x/sync v0.0.0-20200625203802-6e8e738ad208
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/prometheus/common v0.13.0
go: downloading github.com/foxcpp/go-mtasts v0.0.0-20191219193356-62bc3f1f74b8
go: downloading github.com/josharian/intern v1.0.0
go: downloading golang.org/x/sys v0.0.0-20200821140526-fda516888d29
go: downloading github.com/klauspost/compress v1.10.11
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/prometheus/procfs v0.1.3
go: downloading github.com/pierrec/lz4 v2.5.2+incompatible
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/foxcpp/go-imap-namespace v0.0.0-20200722130255-93092adf35f1
go: downloading github.com/martinlindhe/base36 v1.1.0
-- Building maddyctl
go: downloading github.com/urfave/cli v1.22.4
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
--- No scdoc utility found. Skipping man pages building.
-- Copying misc files...
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
```

**Comment by hugmouse** [comment] 2020-12-06 02:16
And if you ignore the `build.sh` and directly compile maddy, it will work.

Path:                    `maddy/cmd/maddy`
Build command: `go build -v  .` 
Status:                 `success`
```
mysh@myshs-MacBook-Pro maddy % go build -v .
github.com/mattn/go-sqlite3
github.com/foxcpp/maddy/internal/table
github.com/foxcpp/go-imap-sql
github.com/foxcpp/maddy/internal/storage/imapsql
github.com/foxcpp/maddy
github.com/foxcpp/maddy/cmd/maddy
```
-----

Path:                    `maddy/cmd/maddyctl`
Build command: `go build -v  .` 
Status:                 `success`
```
mysh@myshs-MacBook-Pro maddyctl % go build -v .
github.com/foxcpp/maddy/cmd/maddyctl/clitools
github.com/foxcpp/maddy/cmd/maddyctl
```

**Comment by herbygillot** [comment] 2020-12-06 02:21
> Couldn't reproduce your bug, but found a different one.
> 
> Also there is some updates, latest commit is `27ec4fa57da9830824a04d839efa43e8d97b97ce` -- you can try newer `build.sh`.
> 
> Tested MacOS 11.0.1:

OK, so it looks like it works on Big Sur (11.0.1)?

> And if you ignore the build.sh and directly compile maddy, it will work.

I understand that, but it looks like those LDFLAGs are there to serve a purpose in hardening the resulting binary since maddy is meant to be exposed on the Internet to potential malicious interaction.

**Comment by hugmouse** [comment] 2020-12-06 02:23
> > Couldn't reproduce your bug, but found a different one.
> > Also there is some updates, latest commit is `27ec4fa57da9830824a04d839efa43e8d97b97ce` -- you can try newer `build.sh`.
> > Tested MacOS 11.0.1:

> OK, so it looks like it works on Big Sur (11.0.1)?

Unfortunately no, this is just my add-on to your issue. I have a slightly different error really :)

...maybe I can find a way to fix it.

## upd

`install: illegal option -- D` can be fixed by using `-d` instead of `-D`

But now I have `install: illegal option -- t` and for now I don't know how to fix it ^^

## upd 2

I tried to modify the installer, but it requires overengineering lol 

Because `install` in MacOS literally 19 years old from that point.

And also we need to fix ldflags thing somehow

It's probably easier to create a separate `build.sh` for MacOS.

**Comment by foxcpp** [comment] 2020-12-06 11:12
@hugmouse, looks like @herbygillot used the old build.sh. I just replaced it per #316 with one that does not set any LDFLAGS.

**Comment by foxcpp** [comment] 2020-12-06 12:02
e447a830163df99ae4c098a8249628dad4cb26be should fix that. Can you verify?

**Comment by hugmouse** [comment] 2020-12-06 13:24
> [e447a83](https://github.com/foxcpp/maddy/commit/e447a830163df99ae4c098a8249628dad4cb26be) should fix that. Can you verify?

lgtm

![image](https://user-images.githubusercontent.com/44648612/101281342-55c88d80-3809-11eb-8400-47322784e308.png)

**Comment by foxcpp** [comment] 2020-12-06 14:29
Okay, then this can be considered fixed. Thanks for reporting.

**Closed as completed by foxcpp** 2020-12-06 14:29 UTC
Labels: bug

**Comment by herbygillot** [comment] 2020-12-06 16:57
Thanks @foxcpp, I've confirmed the latest build.sh works. Waiting for the next release that includes these changes.
