### ISSUE TITLE
Feature request - Support for Sieve

### ISSUE THREAD

**Issue by angelnu** [foxcpp/maddy#448] opened 2022-01-30 18:07 UTC
# Use case

Implement [Sieve ](http://sieve.info/)in Maddy.

As I run with only Maddy (and later alps, currently Nextcloud as client) and would like to avoid depending on Dovecot I am missing a solution for users to configure their filters without depending on creating scripts manually and asking me to upload to the server.

# Your idea for a solution

- Implement ManageSieve in Maddy so users can use their email clients to upload the filter configs to the server
  - this could be either be implemented natively in Go or call existing (but old) [Python libraries ](https://github.com/miracle2k/pysieved). The protocol looks simple enough so re-implementing in Go might even be easier so we could reuse the STARTTLS support in Maddy.
- Add a Sieve parser to Maddy to process the uploaded scripts and generate the scripts out of the sieve configs. Here we could use the [C library libsieve](https://github.com/sodabrew/libsieve) as re-implementing in Go might be more work.

- [x] I'm willing to help with the implementation

**Comment by foxcpp** [comment] 2022-02-01 19:41
Duplicate of #53.

**Closed as completed by foxcpp** 2022-02-01 19:41 UTC
Labels: new feature
