### ISSUE TITLE
Allow sending from whitelisted IPs only

### ISSUE THREAD

**Issue by rawtaz** [foxcpp/maddy#355] opened 2021-05-30 20:52 UTC
# Use case

Would like to be able to configure maddy to only allow incoming SMTP transactions from a list of IPs/CIDRs.

Use case is when you don't have a firewall in front of it and when you don't use authentication.

# Your idea for a solution

Introduce some kind of configuration option where one can define a list of one or more IPs and/or CIDRs, and a way to use that list in e.g. the SMTP endpoint or wherever it makes sense to define that incoming SMTP transactions will only be allowed from these IPs.

- [x] I'm willing to help with the testing

**Comment by foxcpp** [comment] 2021-05-31 18:07
Duplicate of #297.

**Closed as completed** 2021-05-31 18:08 UTC
Labels: new feature
